server:
  host: localhost
  port: 9000
  network: tcp

# mysql 已配置主从同步
# salve to read
readDB:
  host: localhost
  port: 3306
  user: root
  password: dcz.20001018
  dbname: study

# master to write
writeDB:
  host: localhost
  port: 3306
  user: root
  password: dcz.20001018
  dbname: study
